### ISSUE TITLE
num() arguments error after updating to streamlink 5.4.0

### ISSUE THREAD

**Issue by WolfganP** [back-to/generic#20]
Hi, after updating to v5.4.0, I got an error at streamlink initialization:

Linux:
```
$ streamlink https://www.youtube.com/watch?v=IxmWPvIYa1k
Traceback (most recent call last):
  File "/home/pi/.local/bin/streamlink", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.9/site-packages/streamlink_cli/main.py", line 889, in main
    setup_plugins(args.plugin_dirs)
  File "/home/pi/.local/lib/python3.9/site-packages/streamlink_cli/main.py", line 705, in setup_plugins
    load_plugins(PLUGIN_DIRS, showwarning=False)
  File "/home/pi/.local/lib/python3.9/site-packages/streamlink_cli/main.py", line 616, in load_plugins
    success = streamlink.load_plugins(str(directory))
  File "/home/pi/.local/lib/python3.9/site-packages/streamlink/session.py", line 640, in load_plugins
    mod = load_module(module_name, path)
  File "/home/pi/.local/lib/python3.9/site-packages/streamlink/utils/module.py", line 14, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/pi/.local/share/streamlink/plugins/generic.py", line 305, in <module>
    type=num(int, min=0, max=25),
TypeError: num() got an unexpected keyword argument 'min'
```

Windows:
```
> streamlink.exe https://www.youtube.com/watch?v=IxmWPvIYa1k
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] Defining global plugin arguments is deprecated. Use the session options instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
[warnings][streamlinkdeprecation] `streamlink.plugin.api.validate.text` is deprecated. Use `str` instead.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\_Downloads\TV+Streaming\youtubedl-streamlink\bin\streamlink.exe\__main__.py", line 18, in <module>
  File "D:\_Downloads\TV+Streaming\youtubedl-streamlink\pkgs\streamlink_cli\main.py", line 889, in main
    setup_plugins(args.plugin_dirs)
  File "D:\_Downloads\TV+Streaming\youtubedl-streamlink\pkgs\streamlink_cli\main.py", line 705, in setup_plugins
    load_plugins(PLUGIN_DIRS, showwarning=False)
  File "D:\_Downloads\TV+Streaming\youtubedl-streamlink\pkgs\streamlink_cli\main.py", line 616, in load_plugins
    success = streamlink.load_plugins(str(directory))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_Downloads\TV+Streaming\youtubedl-streamlink\pkgs\streamlink\session.py", line 640, in load_plugins
    mod = load_module(module_name, path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\_Downloads\TV+Streaming\youtubedl-streamlink\pkgs\streamlink\utils\module.py", line 14, in load_module
    spec.loader.exec_module(mod)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\defuser\AppData\Roaming\streamlink\plugins\generic.py", line 305, in <module>
    type=num(int, min=0, max=25),
         ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: num() got an unexpected keyword argument 'min'
```

Went back to v5.3.1 and everything runs as normal. 
Thx as always!

**Comment by WolfganP** [comment]
It seems `min=` was replaced by `ge=` at https://github.com/streamlink/streamlink/commit/33d9790b074c4f1911a7f9b4c68a943bbb6f5230 (and `max=` by `le=` as well)

Line https://github.com/back-to/generic/blob/master/plugins/generic.py#LL305C34-L305C34 works once edited to: `type=num(int, ge=0, le=25),`
